# Generated by Django 2.2.12 on 2020-06-08 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('is_electronne_bank', '0002_project_avtor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='function',
            options={'verbose_name': 'Функции', 'verbose_name_plural': 'Функции'},
        ),
        migrations.AlterModelOptions(
            name='functionvproject',
            options={'verbose_name': 'Функции в проекте', 'verbose_name_plural': 'Функции в проекте'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организация'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Партнеры', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AlterModelOptions(
            name='partnervproject',
            options={'verbose_name': 'Партнеры в проекте', 'verbose_name_plural': 'Партнеры в проекте'},
        ),
        migrations.AlterModelOptions(
            name='perspektiveispolzovaniarezultatovproektavmassovoipraktike',
            options={'verbose_name': 'Перспективы использования проекта в массовой практике', 'verbose_name_plural': 'Перспективы использования проекта в массовой практике'},
        ),
        migrations.AlterModelOptions(
            name='planrealizachiivproekte',
            options={'verbose_name': 'План реализации проекта', 'verbose_name_plural': 'План реализации проекта'},
        ),
        migrations.AlterModelOptions(
            name='prognozrazvitiaproekta',
            options={'verbose_name': 'Прогноз развития проекта', 'verbose_name_plural': 'Прогноз развития проекта'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проекты', 'verbose_name_plural': 'Проекты'},
        ),
    ]
