# Generated by Django 2.2.12 on 2020-06-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_electronne_bank', '0002_auto_20200607_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='function',
            options={'verbose_name': 'Функции', 'verbose_name_plural': 'Функции'},
        ),
        migrations.AlterModelOptions(
            name='functionvproject',
            options={'verbose_name': 'Функции в проекте', 'verbose_name_plural': 'Функции в проекте'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организация'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Организация-партнер', 'verbose_name_plural': 'Организация-партнер'},
        ),
        migrations.AlterModelOptions(
            name='partnervproject',
            options={'verbose_name': 'Партнер в проекте', 'verbose_name_plural': 'Партнер в проекте'},
        ),
        migrations.AlterModelOptions(
            name='perspektiveispolzovaniarezultatovproektavmassovoipraktike',
            options={'verbose_name': 'Перспективы использования проекта в масовой практике', 'verbose_name_plural': 'Перспективы использования проекта в массовой практике'},
        ),
        migrations.AlterModelOptions(
            name='planrealizachiivproekte',
            options={'verbose_name': 'План реализации в проекте', 'verbose_name_plural': 'План реализации в проекте'},
        ),
        migrations.AlterModelOptions(
            name='prognozrazvitiaproekta',
            options={'verbose_name': 'Прогноз развития проекта', 'verbose_name_plural': 'Прогноз развития проекта'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='project',
            name='provereno',
            field=models.BooleanField(default=False, verbose_name='Отметка о отсутсвии ошибок'),
        ),
    ]
