# Generated by Django 2.2.12 on 2020-06-03 13:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_v_projet', models.CharField(max_length=250, verbose_name='Функции в проекте')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_organization', models.CharField(max_length=200, verbose_name='Наименование организации')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_partners', models.CharField(max_length=250, verbose_name='Название партнера')),
            ],
        ),
        migrations.CreateModel(
            name='PerspektiveIspolzovaniaRezultatovProektaVmassovoiPraktike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perspektive_ispolzovania_produkta_innovation_deitelnosti', models.CharField(max_length=100, verbose_name='Перспективы использования')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=250, verbose_name='Наименование проекта')),
                ('data_realizachii_s', models.DateField(default=django.utils.timezone.now, verbose_name='Дата реализации с')),
                ('data_realizachii_po', models.DateField(default=django.utils.timezone.now, verbose_name='Дата реализации по')),
                ('selka_na_saite', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на сайте')),
                ('product_innovation_deatelnosti', models.CharField(max_length=250, verbose_name='Продукт инновационной деятельности')),
                ('rukovoditel_organization', models.CharField(blank=True, max_length=250, null=True, verbose_name='Руководитель организации')),
                ('nauche_rukovoditel', models.CharField(blank=True, max_length=250, null=True, verbose_name='Научный руководитель')),
                ('predloshenie_po_ispolzovanie', models.CharField(blank=True, max_length=250, null=True, verbose_name='Предложения по использованию')),
                ('name_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_electronne_bank.Organization', verbose_name='Наименование организации')),
            ],
        ),
        migrations.CreateModel(
            name='PrognozRazvitiaProekta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zadacha_prognoza', models.CharField(max_length=100, verbose_name='Задача прогноза развития')),
                ('name_product', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('kratkoe_opisanie', models.CharField(max_length=100, verbose_name='Краткое описание проекта')),
                ('sroki_realizachii_s', models.DateField(default=django.utils.timezone.now, verbose_name='Сроки реализации с')),
                ('sroki_realizachii_po', models.DateField(default=django.utils.timezone.now, verbose_name='Сроки реализации по')),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prognoz_razvitia_projecta', to='is_electronne_bank.Project', verbose_name='Айди проекта')),
            ],
        ),
        migrations.CreateModel(
            name='PlanRealizachiiVProekte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zadacha', models.CharField(max_length=100, verbose_name='Задача')),
                ('kratoe_naimenovanie', models.CharField(max_length=100, verbose_name='Краткое наименование')),
                ('sroki_s', models.DateField(default=django.utils.timezone.now, verbose_name='Сроки с')),
                ('sroki_po', models.DateField(default=django.utils.timezone.now, verbose_name='Сроки по')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_realizachiiVproekte', to='is_electronne_bank.Project', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerVProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_partner', to='is_electronne_bank.Project', verbose_name='Функции')),
                ('parters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='is_electronne_bank.Partner', verbose_name='Партнеры')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projec_partners', to='is_electronne_bank.Project', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='FunctionVProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_function', models.CharField(max_length=100, verbose_name='Название функции')),
                ('id_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functionVproject', to='is_electronne_bank.Project', verbose_name='Айди функции')),
            ],
        ),
    ]
