# Generated by Django 2.2.12 on 2020-06-18 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('is_electronne_bank', '0003_auto_20200616_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avtor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='provereno',
            field=models.BooleanField(default=False, verbose_name='Отметка об отсутсвии ошибок'),
        ),
    ]
